# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Update file
on:
  schedule:
  - cron: '00 14 * * *'
  workflow_dispatch:
jobs:
  sh-update-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download the subscribe
      run: |
        sh ./auto_update.sh
    - name: Commit Changes
      run: |
       git config --global user.email action-auto@github.com
       git config --global user.name action
       git add .
       git commit -m"由github actions推送,日期:`date`"
       git pull --rebase
    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: main
 
